### ISSUE TITLE
namadac shielded-sync use high resource

### ISSUE THREAD

**Issue by quangtuyen88** [anoma/namada#2874]
I have been running command `namadac shielded-sync` for awhile and see load of my server is increasing 
```
13553 root      20   0 1261672 199980  19628 R  99.7   0.3   4:54.17 namadac shielded-sync
```
![24110](https://github.com/anoma/namada/assets/5916248/a8ddb0a7-7795-4323-a380-b0084e45b4ce)

**Comment by spidey-169** [comment]
> I have been running command `namadac shielded-sync` for awhile and see load of my server is increasing
> 
> ```
> 13553 root      20   0 1261672 199980  19628 R  99.7   0.3   4:54.17 namadac shielded-sync
> ```
> 
> ![24110](https://private-user-images.githubusercontent.com/5916248/311486080-a8ddb0a7-7795-4323-a380-b0084e45b4ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTQ2ODAsIm5iZiI6MTcxMDA1NDM4MCwicGF0aCI6Ii81OTE2MjQ4LzMxMTQ4NjA4MC1hOGRkYjBhNy03Nzk1LTQzMjMtYTM4MC1iMDA4NGU0NWI0Y2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMDcwNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzc2ODUxZTRhOTI2MDBlOGRjMThiZGI4YmNjZDk5YWYwMDQ0ODAyNmZkYmJmOTY5Y2JkYWEyYjVhMWNlODFmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G7yYZCPtoX5BJkVWg-Aynawg8h2L9pAAKTofP6CYQEc)

Guessing its expecting during syncing, as its performing heavy computations

**Comment by spidey-169** [comment]
I am not seeing such high cpu usage, only memory usage shoots up during syncing

**Comment by quangtuyen88** [comment]
I guess you need to run it for long time to able to see CPU consuming . 
it will consuming high CPU at `scan` step

**Comment by spidey-169** [comment]
> I guess you need to run it for long time to able to see CPU consuming . it will consuming high CPU at `scan` step

Ran it for 8 hrs before I faced the error I posted 😓

**Comment by spidey-169** [comment]
> I guess you need to run it for long time to able to see CPU consuming . it will consuming high CPU at `scan` step

Its likely, Guessing scan is a compute intensive step. But again, once done, subsequent scans should be less intense. Also make sure to have specs slightly higher than recommended. 4-6cpu should resolve this too

**Comment by quangtuyen88** [comment]
Yes but I'm using 16 CPUs
```
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 7 7700 8-Core Processor
  ```
  still see high CPU consumption... The fact is shield transaction will be used many times when Namada goes live on Mainnet i don't know why the team does not fix or improve that importal command.
Took me the same a half of day to full sync and more 3 hours more after i have done sync at the first time to resync.

**Comment by spidey-169** [comment]
> Yes but I'm using 16 CPUs
> 
> ```
> CPU(s):                  16
>   On-line CPU(s) list:   0-15
> Vendor ID:               AuthenticAMD
>   Model name:            AMD Ryzen 7 7700 8-Core Processor
> ```
> 
> still see high CPU consumption... The fact is shield transaction will be used many times when Namada goes live on Mainnet i don't know why the team does not fix or improve that importal command. Took me the same a half of day to full sync and more 3 hours more after i have done sync at the first time to resync.

Guessing its on their TODO list, this is a testnet, good to bring forth this here

**Comment by brentstone** [comment]
Will close this now, but tracking in #2900.
